apiVersion: v1
clusters:
- cluster:
    server: $KUBE_ADDR
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: $PWD/apiserver.crt
    client-key: $PWD/apiserver.key
