apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: $KUBE_ADDR
  name: $CLUSTER_NAME
contexts:
- context:
    cluster: $CLUSTER_NAME
    namespace: $CLUSTER_NAMESPACE
    user: user
  name: $CLUSTER_NAME
current-context: $CLUSTER_NAME
kind: Config
preferences: {}
users:
- name: user
  user:
    token:
      $KUBE_TOKEN
